### ISSUE TITLE
Is it possible to improve the resolution to 512x512 or 1024x1024?

### ISSUE THREAD

**Issue by BeaverInGreenland** [samsartor/matfusion#1]
Thank you for your work! 
As I skimmed through your paper, I saw that you produce SVBRDF maps of 256x256. Is there a way to generate bigger svbrdf maps?

**Comment by samsartor** [comment]
Yes that is definitely a good project for future work and I've already bounced around a few ideas. Breaking the input into tiles would be pretty straightforward, or we could do something along the lines of Deep Floyd IF with a cascading series of U-Nets!

If anyone wants to work on that sort of thing, definitely let me know.
