### ISSUE TITLE
mode.json unavailable

### ISSUE THREAD

**Issue by BeaverInGreenland** [samsartor/matfusion#2]
Hello,
When I try to run `model = Model.from_checkpoint('./checkpoints/flash_v1_jax/')` from `matfusion_jax_flash_demo.ipynb` I encounter the following error: `FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/flash_v1_jax/mode.json'`

Could you tell me how to solve this error, please? The checkpoints don't seem to have `mode.json`, and it doesn't work if we replace it by `config.json`.

**Comment by samsartor** [comment]
Did you download and  untar  `https://www.cs.wm.edu/~ppeers/publications/Sartor2023MFA/data/flash_v1_jax.tar.lz4`  into the checkpoints directory? If there is no `mode.json` inside the tar.lz4 archive then I definitely need to re-upload it!

Edit: I checked and the `mode.json` file is definitely in the archive. Once you extract it, check that your checkpoints directory looks like:
```
checkpoints
└── flash_v1_jax
    ├── checkpoint.msgpack
    ├── LICENSE.txt
    └── mode.json
```
