### ISSUE TITLE
Training/finetuning code in diffusers

### ISSUE THREAD

**Issue by HarryWang355** [samsartor/matfusion#5]
Thank you for this amazing work!

I notice that there are pre-trained checkpoints and demos in both Jax and Diffusers frameworks, but the training code only support sJax. Would it be possible to also release the diffusers version of the training code? I'm trying to finetune your model on a customized dataset and would need the resulting model to be a diffusers checkpoint.

**Comment by samsartor** [comment]
I don't think it will happen before the SIGGRAPH Asia deadline because I have other work to do, but yah. Providing some diffusers-based training/finetuning scripts makes a lot of sense.
