### ISSUE TITLE
Unconditional generation using pretrained backbone checkpoint

### ISSUE THREAD

**Issue by gerwang** [samsartor/matfusion#6]
Hi @samsartor,

Thanks for your amazing work! I'm pretty interested in your code, and want to use the pretrained backbone ([unconditional_v1_diffusers.tar.lz4](https://www.cs.wm.edu/~ppeers/publications/Sartor2023MFA/data/unconditional_v1_diffusers.tar.lz4)) to generate random BRDFs without conditions. However, the generated output does not make sense. Could you please help me find out what is wrong?

Here is my attempt by modifying the [matfusion_diffusers_flash_demo.ipynb](https://github.com/samsartor/matfusion/blob/main/matfusion_diffusers_flash_demo.ipynb):

```python
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import os
os.environ['CUDA_VISIBLE_DEVICES'] = '3'


# In[2]:


from diffusers import EulerAncestralDiscreteScheduler, DDIMScheduler, UNet2DModel, DDPMScheduler


# In[3]:


from matfusion_jax.vis import display_image, display_svbrdf, show_svbrdf


# In[4]:


import imageio.v3 as iio
import cv2
import numpy as np
import torch
from pathlib import Path
from tqdm import tqdm


# # Model Loading

# In[5]:


device = 'cuda'


# In[6]:


model = UNet2DModel.from_pretrained('./checkpoints/unconditional_v1_diffusers/').to(device)


# # Run MatFusion using Huggingface Diffusers

# In[7]:


euler_a_schedule = EulerAncestralDiscreteScheduler(
    beta_schedule='linear',
    prediction_type='v_prediction',
    timestep_spacing="linspace",
)
ddim_schedule = DDIMScheduler(
    beta_schedule='linear',
    prediction_type='v_prediction',
    rescale_betas_zero_snr=True,
    clip_sample=False,
    timestep_spacing="linspace",
)
ddpm_schedule = DDPMScheduler(
    beta_schedule='linear',
    prediction_type='v_prediction',
    clip_sample=False,
    timestep_spacing="linspace",
)
schedule = euler_a_schedule
schedule.set_timesteps(20)
timestep_mult = model.config.get('timestep_mult', 1/1000)
vis_freq = 1


# In[8]:


diffusion_frames = []

with torch.no_grad():
    y = torch.randn(1, 10, 256, 256, device=device, dtype=torch.float32)
    y = y * schedule.init_noise_sigma

    for t in tqdm(schedule.timesteps):
        noisy_svbrdf = schedule.scale_model_input(y, t)
        model_output = model(
            noisy_svbrdf,
            t*timestep_mult,
        ).sample

        step_output = schedule.step(model_output, t, y)
        y = step_output.prev_sample

        svbrdf_est = (step_output.pred_original_sample * 0.5 + 0.5).clamp(0, 1).permute(0, 2, 3, 1).cpu().numpy()
        if int(t) % vis_freq == 0:
            diffusion_frames.append(svbrdf_est)

show_svbrdf(np.concatenate(diffusion_frames), horizontal=True, gamma=2.2)


# In[9]:


svbrdf_img = display_svbrdf(svbrdf_est[0], horizontal=True, format='png', gamma=2.2)
Path('./demo/pink_svbrdf.png').write_bytes(svbrdf_img.data) # optional: save the svbrdf to disk
svbrdf_img
```

Here is the generated result:

![image](https://github.com/samsartor/matfusion/assets/25758401/102639fc-890c-4824-a69d-9412b45bc295)

Also, I really appreciate that if there will be a official demo using the pretrained backbone, and think many people will find the backbone interesting.

Thank you!

**Comment by samsartor** [comment]
Thanks for your interest! I don't see any issues with this right off the bat. Have you installed our diffusers fork from the submodule in this repo?

Edit: also note that the unconditional model does not make anything particularly interesting, but these results are definitely wrong

**Comment by gerwang** [comment]
> Have you installed our diffusers fork from the submodule in this repo?

Yes, I installed the fork as a submodule.

I also tried a jax version of the unconditional generation, and get almost exactly the same result. Here is the jax version code:

```python
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import os
os.environ['CUDA_VISIBLE_DEVICES'] = '3'


# In[2]:


from matfusion_jax.vis import IPythonReport, display_image, display_svbrdf
from matfusion_jax.model import Model
from matfusion_jax.nprast import nprast_animated_render


# In[3]:


import imageio.v3 as iio
import cv2
import numpy as np
import jax
from pathlib import Path


# # Model Loading

# In[4]:


model = Model.from_checkpoint('./checkpoints/unconditional_v1_jax/')


# # Input Loading

# In[5]:


# TODO: pick your own image
image = iio.imread('./demo/pink_input.png')
image = cv2.resize(image, (256, 256))
image = np.expand_dims(image / 255.0, 0)
image = image ** 2.2
display_image(image, gamma=2.2)


# # Run MatFusion

# In[ ]:


fov = 45 # TODO: accurate FOV can make a pretty big quality difference
distance = 1/np.tan(np.deg2rad([fov])/2)

results = model.evaluate(
    {
        'input': image,
        'flash_x': np.array([0.0]),
        'flash_y': np.array([0.0]),
        'view_distance': distance,
        'flash_distance': distance,
    },
    # TODO: you can also improve quality by selecting a good seed
    key=jax.random.PRNGKey(0),
    sampler='euler_a',
    steps=20,
    animation='signal',
)


# # See the Results

# In[ ]:


svbrdf_img = display_svbrdf(results['svbrdf_est'][0], horizontal=True, format='png', gamma=2.2)
Path('./demo/pink_svbrdf.png').write_bytes(svbrdf_img.data) # optional: save the svbrdf to disk
svbrdf_img


# In[ ]:


display_svbrdf(results['svbrdf_animation'][0], horizontal=True, gamma=2.2)


# In[ ]:


display_image(nprast_animated_render(results['svbrdf_est'][0]), gamma=2.2)


# In[ ]:

```

and here is the result:

![pink_svbrdf](https://github.com/samsartor/matfusion/assets/25758401/fdaf910b-e8f6-489f-bfec-7a208388a88f)

I believe my result can be replicated using the above code, which is adapted from the original notebooks with minor modifications. If there is anything wrong in this code, please kindly point it out. Thank you!

**Comment by gerwang** [comment]
I also wonder shall we expect that the backbone can generate diverse and high quality SVBRDFs? I am not quite sure about what is the meaning of "unconditional model does not make anything particularly interesting".

**Comment by samsartor** [comment]
@gerwang Can you try this model link: https://www.cs.wm.edu/~ppeers/publications/Sartor2023MFA/data/unconditional_v1_corrected_diffusers.tar.lz4 

> I also wonder shall we expect that the backbone can generate diverse and high quality SVBRDFs?

Not particularly.  Here is an example from a minute ago:
![image](https://github.com/samsartor/matfusion/assets/1740180/79fc33b3-ae4b-4463-9376-85e88fab0b07)

In general diffusion models only produce interesting output when conditioned, if even just a onehot category or something.

**Comment by gerwang** [comment]
Thank you very much for the update! I can confirm that the updated checkpoint works, here are some examples I generated (with DDPMScheduler):
![pink_svbrdf_1](https://github.com/samsartor/matfusion/assets/25758401/04530a86-4121-4c9e-9991-06da6754eff5)
![pink_svbrdf_2](https://github.com/samsartor/matfusion/assets/25758401/713b5d4f-0997-42da-8042-d75974f9620a)
![pink_svbrdf_3](https://github.com/samsartor/matfusion/assets/25758401/75547162-6d50-419d-9912-6d4a3840eb30)

My thoughts on the ability of unconditional model: The outputs are not as interesting as conditioned ones, because it cannot match a user's requirement, thus conditioning the diffusion model is considered a significant contribution. However, there is a chance that a particular high quality material can be generated by a random noise, so the generation abilities of the conditioned variants all come from the uncoditional one. So I assume the generated results show that the unconditional model works as expected.
